-- CareerIQ platform extensions (run after career_iq_database.sql)
-- Safe to re-run: uses IF NOT EXISTS where possible

-- Resume extracted content for AI flows
ALTER TABLE public.resumes ADD COLUMN IF NOT EXISTS extracted_text TEXT;
ALTER TABLE public.resumes ADD COLUMN IF NOT EXISTS parsed_data JSONB;

-- Application matching + quiz gate tracking
ALTER TABLE public.applications ADD COLUMN IF NOT EXISTS match_score NUMERIC(5,2);
ALTER TABLE public.applications ADD COLUMN IF NOT EXISTS match_details JSONB;
ALTER TABLE public.applications ADD COLUMN IF NOT EXISTS quiz_status VARCHAR(30) DEFAULT 'Not Started';
ALTER TABLE public.applications ADD COLUMN IF NOT EXISTS quiz_passed BOOLEAN DEFAULT FALSE;
ALTER TABLE public.applications ADD COLUMN IF NOT EXISTS best_quiz_score NUMERIC(5,2);

-- Job skill requirement flag
ALTER TABLE public.job_skills ADD COLUMN IF NOT EXISTS is_required BOOLEAN DEFAULT TRUE;

-- Interview session lifecycle
ALTER TABLE public.interview_sessions ADD COLUMN IF NOT EXISTS status VARCHAR(30) DEFAULT 'Scheduled';
ALTER TABLE public.interview_sessions ADD COLUMN IF NOT EXISTS duration_seconds INTEGER;

-- Richer final evaluation storage
ALTER TABLE public.interview_evaluation ADD COLUMN IF NOT EXISTS overall_score NUMERIC(5,2);
ALTER TABLE public.interview_evaluation ADD COLUMN IF NOT EXISTS problem_solving_score NUMERIC(5,2);
ALTER TABLE public.interview_evaluation ADD COLUMN IF NOT EXISTS recommendation TEXT;
ALTER TABLE public.interview_evaluation ADD COLUMN IF NOT EXISTS strengths TEXT;
ALTER TABLE public.interview_evaluation ADD COLUMN IF NOT EXISTS weaknesses TEXT;

-- Quiz attempts (job-specific gate before AI interview)
CREATE TABLE IF NOT EXISTS public.quiz_attempts (
    attempt_id SERIAL PRIMARY KEY,
    application_id INTEGER NOT NULL REFERENCES public.applications(application_id) ON DELETE CASCADE,
    student_id INTEGER NOT NULL REFERENCES public.students(student_id) ON DELETE CASCADE,
    job_id INTEGER NOT NULL REFERENCES public.jobs(job_id) ON DELETE CASCADE,
    score NUMERIC(5,2),
    passed BOOLEAN DEFAULT FALSE,
    total_questions INTEGER NOT NULL DEFAULT 10,
    correct_answers INTEGER DEFAULT 0,
    started_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    status VARCHAR(20) DEFAULT 'In Progress'
);

CREATE TABLE IF NOT EXISTS public.quiz_questions (
    question_id SERIAL PRIMARY KEY,
    attempt_id INTEGER NOT NULL REFERENCES public.quiz_attempts(attempt_id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    options JSONB NOT NULL,
    correct_option_index INTEGER NOT NULL,
    question_order INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS public.quiz_answers (
    answer_id SERIAL PRIMARY KEY,
    attempt_id INTEGER NOT NULL REFERENCES public.quiz_attempts(attempt_id) ON DELETE CASCADE,
    question_id INTEGER NOT NULL REFERENCES public.quiz_questions(question_id) ON DELETE CASCADE,
    selected_option_index INTEGER,
    is_correct BOOLEAN
);

-- Compatibility with an earlier quiz schema already present in some CareerIQ
-- databases. These additive columns let application-scoped screening coexist
-- with legacy quiz_id/quiz_question_id records without deleting or rewriting
-- existing data.
ALTER TABLE public.quiz_attempts ADD COLUMN IF NOT EXISTS application_id INTEGER;
ALTER TABLE public.quiz_attempts ADD COLUMN IF NOT EXISTS job_id INTEGER;
ALTER TABLE public.quiz_attempts ADD COLUMN IF NOT EXISTS total_questions INTEGER NOT NULL DEFAULT 10;
ALTER TABLE public.quiz_attempts ADD COLUMN IF NOT EXISTS correct_answers INTEGER DEFAULT 0;
ALTER TABLE public.quiz_attempts ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'In Progress';

ALTER TABLE public.quiz_questions ADD COLUMN IF NOT EXISTS attempt_id INTEGER;
ALTER TABLE public.quiz_questions ADD COLUMN IF NOT EXISTS question_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.quiz_questions ADD COLUMN IF NOT EXISTS question_text TEXT;
ALTER TABLE public.quiz_questions ADD COLUMN IF NOT EXISTS options JSONB;
ALTER TABLE public.quiz_questions ADD COLUMN IF NOT EXISTS correct_option_index INTEGER;
ALTER TABLE public.quiz_questions ADD COLUMN IF NOT EXISTS question_order INTEGER;

ALTER TABLE public.quiz_answers ADD COLUMN IF NOT EXISTS question_id INTEGER;
ALTER TABLE public.quiz_answers ADD COLUMN IF NOT EXISTS selected_option_index INTEGER;

CREATE INDEX IF NOT EXISTS idx_quiz_attempts_application ON public.quiz_attempts(application_id);
CREATE INDEX IF NOT EXISTS idx_quiz_attempts_student ON public.quiz_attempts(student_id);
CREATE INDEX IF NOT EXISTS idx_interview_sessions_application ON public.interview_sessions(application_id);

CREATE TABLE IF NOT EXISTS public.interview_integrity_events (
    event_id BIGSERIAL PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES public.interview_sessions(session_id) ON DELETE CASCADE,
    event_type VARCHAR(60) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    details JSONB,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.interview_integrity_events ADD COLUMN IF NOT EXISTS session_id INTEGER;
ALTER TABLE public.interview_integrity_events ADD COLUMN IF NOT EXISTS event_type VARCHAR(60);
ALTER TABLE public.interview_integrity_events ADD COLUMN IF NOT EXISTS severity VARCHAR(20);
ALTER TABLE public.interview_integrity_events ADD COLUMN IF NOT EXISTS details JSONB;
ALTER TABLE public.interview_integrity_events ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_integrity_events_session ON public.interview_integrity_events(session_id, created_at);
